name: github-actions-test

on:
  push:
    branches: [main]

jobs:
  print-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v5.0.0

      - name: docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        
      - name: install JDK 21
        uses: actions/setup-java@v5.0.0
        with: 
          java-version: '21'
          distribution: 'temurin'

      - name: build spring boot app
        run: |
          cd backend
          chmod 777 ./mvnw
          ./mvnw clean package -DskipTests
          docker build -t ${{ secrets.DOCKER_USERNAME }}/spring-app:lastest .
          docker push ${{ secrets.DOCKER_USERNAME }}/spring-app:lastest
