name: github-actions-test

on:
  push:
    branches: [main]

jobs:
  print-test:
    runs-on: ubuntu-latest

    steps:
      - name: dir list print1
        run: ls -a
        
      - name: checkout
        uses: actions/checkout@v5.0.0

      - name: dir list print2
        run: ls -a

      - name: install JDK 21
        uses: actions/setup-java@v5.0.0
        with: 
          java-version: '21'
          distribution: 'temurin'

      - name: build spring boot app
        run: |
          cd backend
          chmod 777 ./mvnw
          ./mvnw clean package -DskipTests
          cd target
          ls -a
